server:
  tomcat:
    #最大工作线程数
    max-threads: 500
    #最小备用线程数
    min-spare-threads: 50

spring:
  redis:
    host: 47.98.252.163
    port: 6379
    timeout: 5000
    password: GMadmins1318#
    database: 14
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

ribbon:
  eager-load:
    enabled: true
    clients: kanon-auth,kanon-upms-service

feign:
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

server:
  auth:
    #认证服务的服务名
    name: kanon-auth
  upms:
    #通用登录服务的服务名
    name: kanon-upms-server
