server:
  tomcat:
    #最大工作线程数
    max-threads: 500
    #最小备用线程数
    min-spare-threads: 50
  auth:
    #认证服务的服务名
    name: kanon-auth
  upms:
    #通用登录服务的服务名
    name: kanon-upms-server

spring:
  redis:
    host: 10.2.21.228
    port: 6379
    timeout: 5000
  rabbitmq:
    host: 10.2.21.228
    port: 5672
    name: other
    password: admin
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  session:
    store-type: none

ribbon:
  eager-load:
    enabled: true
    clients: kanon-auth,kanon-upms-service

feign:
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000

#监控短点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false
