server:
  port: 60000

spring:
  sleuth:
    sampler:
      percentage: 0.2

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ratelimit:
    key-prefix: kanon-ratelimite
    enabled: true
    #使用redis存储,必须大写
    repository: REDIS
    behind-proxy: true
    policies:
      pig-upms-service:
        limit: 100
        quota: 100
        refresh-interval: 3

security:
  validate:
    #开启验证码验证过滤器
    code: false
    #演示环境过滤器
    preview: false
  sessions: stateless
  oauth2:
    client:
      client-id: kanon
      client-secret: kanon
    resource:
      loadBalanced: true
      token-info-uri: ${security.auth.server}/oauth/check-token
      service-id: kanon-gateway
      jwt:
         key-uri: ${security.auth.server}/oauth/token_key #解析jwt令牌所需要密钥的地址
auth:
  ignore:
    urls:
      - /mobile/**
      - /auth/**
      - /admin/code/*
      - /admin/smsCode/*
      - /admin/user/info
      - /admin/menu/userMenu
      - /swagger-resources/**
      - /swagger-ui.html
      - /*/v2/api-docs
      - /swagger/api-docs
      - /webjars/**
    clients:
      - app
